const skills = [
  { name: "JavaScript" , skill: 80},
  { name: "React.JS", skill: 90},
  { name: "Node.JS", skill: 90},
  { name: "PostgreSQL", skill: 86},
  { name: "Linux", skill: 96},
  { name: "Terminal", skill: 94},
  { name: "Shell Script", skill: 82},
  { name: "Git" , skill: 80},
  { name: "Culture DevOps", skill: 80},
  { name: "API RESTful" , skill: 84},
  { name: "HTML", skill: 79},
  { name: "CSS" , skill: 79},
  { name: "SASS", skill: 60},
  { name: "Styled Componentes", skill: 78},
  { name: "Architecture MVC", skill: 78},
  { name: "Typescript", skill: 68},
  { name: "React Native", skill: 60},
  { name: "SQL", skill: 58},
  { name: "Scrum", skill: 72},
  { name: "BPO", skill: 76},
  { name: "PHP", skill: 40},
  { name: "Phyton", skill: 20},
  { name: "PDV", skill: 16},
  { name: "Docker", skill: 40},
  { name: "Architecture DDD", skill: 30},
  { name: "MongoDB", skill: 42},
  { name: "Unit Tests", skill: 23},
]

export default skills;
